DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS associations;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE user_assoc (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  association TEXT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user (id)
);